/* MMDE browser bundle. GENERATED by scripts/build-web.mjs from src/. Do not edit. */
(() => {
  // data/seeds/slime.sample.json
  var slime_sample_default = {
    _status: "UNVERIFIED SAMPLE. Built from web-search result summaries (2026-10-08), not from checked primary pages. Must be verified against official sources before it counts as ground truth. Season 1 plus one movie release only.",
    media: {
      id: "slime",
      type: "anime",
      title: "That Time I Got Reincarnated as a Slime",
      altTitles: [
        "Tensei shitara Slime Datta Ken"
      ],
      year: 2018,
      externalIds: {}
    },
    claims: [
      {
        part: {
          kind: "season",
          number: 1
        },
        role: "opening",
        position: "OP1",
        title: "Nameless Story",
        artists: [
          "Takuma Terashima"
        ],
        source: "https://tensura.fandom.com/wiki/Season_1/Music (via search summary; primary page not read)"
      },
      {
        part: {
          kind: "season",
          number: 1
        },
        role: "opening",
        position: "OP2",
        title: "Meguru Mono",
        artists: [
          "Takuma Terashima"
        ],
        source: "https://tensura.fandom.com/wiki/Season_1/Music (via search summary; primary page not read)"
      },
      {
        part: {
          kind: "season",
          number: 1
        },
        role: "ending",
        position: "ED1",
        title: "Another colony",
        artists: [
          "TRUE"
        ],
        source: "https://tensura.fandom.com/wiki/Season_1/Music (via search summary; primary page not read)"
      },
      {
        part: {
          kind: "season",
          number: 1
        },
        role: "ending",
        position: "ED2",
        title: "Little Soldier",
        artists: [
          "Azusa Tadokoro"
        ],
        source: "https://tensura.fandom.com/wiki/Season_1/Music (via search summary; primary page not read)"
      },
      {
        part: {
          kind: "season",
          number: 1
        },
        role: "insert",
        position: "ep23",
        title: "Boku no Naka no Kimi e",
        artists: [
          "TRUE"
        ],
        source: "https://tensura.fandom.com/wiki/Season_1/Music (via search summary; primary page not read)"
      }
    ],
    releases: [
      {
        title: "Eien no Kizuna: That Time I Got Reincarnated as a Slime the Movie Scarlet Bond Original Soundtrack",
        artists: [
          "Hitoshi Fujima (Elements Garden)"
        ],
        kind: "ost",
        label: "Lantis",
        trackCount: 46,
        part: {
          kind: "movie"
        },
        source: "https://otakumode.com/shop/632a6d81f1c8c1001f7073ce (via search summary; 2 discs, 46 BGM tracks; CD release date not confirmed)"
      }
    ]
  };

  // src/app/organize.ts
  var PART_ORDER = ["season", "movie", "special", "ova", "whole"];
  var ROLE_ORDER = ["opening", "ending", "insert", "character", "ost", "score", "promo", "other"];
  var ROLE_LABEL = {
    opening: "Openings",
    ending: "Endings",
    insert: "Insert Songs",
    character: "Character Songs",
    ost: "OST",
    score: "Original Score",
    promo: "Promotional",
    other: "Other"
  };
  function partLabel(t) {
    const k = t.part.kind;
    const name = k === "season" ? "Season" : k === "movie" ? "Movie" : k === "ova" ? "OVA" : k === "special" ? "Special" : "Whole media";
    return t.part.number != null && k !== "whole" ? `${name} ${t.part.number}` : name;
  }
  function organize(tracks) {
    const sorted = [...tracks].sort(
      (a, b) => PART_ORDER.indexOf(a.part.kind) - PART_ORDER.indexOf(b.part.kind) || (a.part.number ?? 0) - (b.part.number ?? 0) || ROLE_ORDER.indexOf(a.role) - ROLE_ORDER.indexOf(b.role) || (a.position ?? "").localeCompare(b.position ?? "")
    );
    const out = [];
    for (const t of sorted) {
      const label = partLabel(t);
      let part = out.find((p) => p.part === label);
      if (!part) out.push(part = { part: label, roles: [] });
      const roleLabel = ROLE_LABEL[t.role];
      let role = part.roles.find((r) => r.role === roleLabel);
      if (!role) part.roles.push(role = { role: roleLabel, tracks: [] });
      role.tracks.push(t);
    }
    return out;
  }

  // src/providers/types.ts
  function createRateLimiter(intervalMs) {
    let next = 0;
    return async function wait() {
      const now = Date.now();
      const at = Math.max(now, next);
      next = at + intervalMs;
      if (at > now) await new Promise((r) => setTimeout(r, at - now));
    };
  }

  // src/providers/anilist.ts
  var QUERY = `query ($q: String) { Page(perPage: 5) { media(search: $q, type: ANIME) {
  id idMal seasonYear title { romaji english native } synonyms } } }`;
  function aniListResolver(fetchImpl = fetch) {
    const wait = createRateLimiter(1e3);
    return {
      name: "anilist",
      async search(query) {
        await wait();
        const res = await fetchImpl("https://graphql.anilist.co", {
          method: "POST",
          headers: { "Content-Type": "application/json", Accept: "application/json" },
          body: JSON.stringify({ query: QUERY, variables: { q: query } })
        });
        if (!res.ok) throw new Error(`HTTP ${res.status} from AniList`);
        const data = await res.json();
        return (data.data?.Page?.media ?? []).map((m) => ({
          id: `anilist-${m.id}`,
          type: "anime",
          title: m.title.english ?? m.title.romaji ?? m.title.native ?? String(m.id),
          altTitles: [m.title.romaji, m.title.native, ...m.synonyms ?? []].filter((x) => !!x),
          year: m.seasonYear ?? void 0,
          externalIds: { anilist: String(m.id), ...m.idMal ? { mal: String(m.idMal) } : {} }
        }));
      }
    };
  }

  // src/matching/normalize.ts
  var VERSION_PATTERNS = [
    ["tv_size", /\b(tv[\s-]?size|tv[\s-]?ver(?:sion)?|anime[\s-]?size|short[\s-]?ver(?:sion)?)\b/i],
    ["instrumental", /\b(instrumental|karaoke|off[\s-]?vocal)\b/i],
    ["live", /\blive\b/i],
    ["remix", /\b(remix|re[\s-]?mix|mixed by)\b/i],
    ["cover", /\b(cover|tribute|originally performed)\b/i],
    ["rerecording", /\b(re[\s-]?record(?:ed|ing)?|new recording)\b/i],
    ["full", /\b(full[\s-]?(?:size|ver(?:sion)?)|album ver(?:sion)?|extended)\b/i]
  ];
  function classifyVersion(title, disambiguation = "") {
    const text = `${title} ${disambiguation}`;
    for (const [kind, re] of VERSION_PATTERNS) if (re.test(text)) return kind;
    return "original";
  }
  function normalizeTitle(title) {
    let t = title.normalize("NFKC").toLowerCase();
    t = t.replace(/[(\[（][^)\]）]*[)\]）]/g, " ");
    t = t.replace(/\s[-–—]\s.*$/, " ");
    t = t.replace(/[^\p{L}\p{N}\s]/gu, " ");
    return t.replace(/\s+/g, " ").trim();
  }
  function normalizeArtist(name) {
    return name.normalize("NFKC").toLowerCase().replace(/\b(feat\.?|ft\.?|featuring)\b.*$/, " ").replace(/[^\p{L}\p{N}\s]/gu, " ").replace(/\s+/g, " ").trim();
  }
  function levenshtein(a, b) {
    if (a === b) return 0;
    const prev = Array.from({ length: b.length + 1 }, (_, i) => i);
    for (let i = 1; i <= a.length; i++) {
      let diag = prev[0];
      prev[0] = i;
      for (let j = 1; j <= b.length; j++) {
        const tmp = prev[j];
        prev[j] = Math.min(prev[j] + 1, prev[j - 1] + 1, diag + (a[i - 1] === b[j - 1] ? 0 : 1));
        diag = tmp;
      }
    }
    return prev[b.length];
  }
  function similarity(a, b) {
    if (!a && !b) return 1;
    if (!a || !b) return 0;
    return 1 - levenshtein(a, b) / Math.max(a.length, b.length);
  }

  // src/providers/curated.ts
  function seedMatchesMedia(seed, media) {
    if (media.id === seed.media.id) return true;
    const names = (m) => [m.title, ...m.altTitles].map(normalizeTitle).filter(Boolean);
    const mine = new Set(names(seed.media));
    return names(media).some((n) => mine.has(n));
  }
  function curatedProvider(seed) {
    return {
      name: "curated-seed",
      async releases(media) {
        if (!seedMatchesMedia(seed, media)) return [];
        return (seed.releases ?? []).map((r) => ({
          title: r.title,
          artists: r.artists,
          kind: r.kind,
          label: r.label,
          date: r.date,
          trackCount: r.trackCount,
          part: r.part,
          evidence: { provider: "curated-seed", url: r.source, fetchedAt: (/* @__PURE__ */ new Date(0)).toISOString() }
        }));
      },
      async discover(media) {
        if (!seedMatchesMedia(seed, media)) return [];
        return seed.claims.map((c) => ({
          part: c.part,
          role: c.role,
          position: c.position,
          title: c.title,
          artists: c.artists,
          durationSec: c.durationSec,
          evidence: { provider: "curated-seed", url: c.source, fetchedAt: (/* @__PURE__ */ new Date(0)).toISOString() }
        }));
      }
    };
  }

  // src/providers/musicbrainz.ts
  function musicBrainzResolver(userAgent, fetchImpl = fetch) {
    const wait = createRateLimiter(1100);
    return {
      name: "musicbrainz",
      async resolve(title, artists) {
        await wait();
        const q = `recording:"${title.replace(/"/g, "")}"` + (artists[0] ? ` AND artist:"${artists[0].replace(/"/g, "")}"` : "");
        const url = `https://musicbrainz.org/ws/2/recording?query=${encodeURIComponent(q)}&fmt=json&limit=10&inc=isrcs`;
        const res = await fetchImpl(url, { headers: { ...userAgent ? { "User-Agent": userAgent } : {}, Accept: "application/json" } });
        if (!res.ok) throw new Error(`HTTP ${res.status} from MusicBrainz`);
        const data = await res.json();
        return (data.recordings ?? []).map((r) => ({
          title: r.title,
          artists: (r["artist-credit"] ?? []).map((a) => a.name),
          durationSec: r.length ? Math.round(r.length / 1e3) : void 0,
          mbid: r.id,
          isrcs: r.isrcs ?? [],
          disambiguation: r.disambiguation,
          source: "musicbrainz"
        }));
      }
    };
  }

  // src/providers/seedResolver.ts
  function seedMediaResolver(seeds) {
    return {
      name: "local-seeds",
      async search(query) {
        const q = normalizeTitle(query);
        if (!q) return [];
        return seeds.map((s) => s.media).filter((m) => [m.title, ...m.altTitles].some((t) => normalizeTitle(t).includes(q)));
      }
    };
  }

  // src/providers/wikiLlm.ts
  var ROLES = /* @__PURE__ */ new Set(["opening", "ending", "insert", "character", "ost", "score", "promo", "other"]);
  var PART_KINDS = /* @__PURE__ */ new Set(["season", "movie", "special", "ova", "whole"]);
  var PROMPT = (title, text) => `You extract music facts about the media "${title}" from the page text below.
Return ONLY a JSON array. Each item: {"part":{"kind":"season|movie|special|ova|whole","number":<int|null>},"role":"opening|ending|insert|character|ost|score|promo|other","position":"OP1|ED2|...|null","title":"<song title>","artists":["<artist>"],"quote":"<exact verbatim sentence or fragment from the text that states this>"}
Rules: use ONLY what the text states; never guess; if unsure, omit the item; "quote" must be copied exactly from the text.
TEXT:
${text}`;
  function parseClaims(raw, pageText, url, now, provider = "wikipedia+llm") {
    const start2 = raw.indexOf("[");
    const end = raw.lastIndexOf("]");
    if (start2 < 0 || end <= start2) return [];
    let items;
    try {
      items = JSON.parse(raw.slice(start2, end + 1));
    } catch {
      return [];
    }
    if (!Array.isArray(items)) return [];
    const haystack = normalizeTitle(pageText.replace(/\s+/g, " "));
    const out = [];
    for (const it of items) {
      const title = typeof it.title === "string" ? it.title.trim() : "";
      const quote = typeof it.quote === "string" ? it.quote.trim() : "";
      const role = it.role;
      const part = it.part;
      if (!title || !quote || !ROLES.has(role) || !part || !PART_KINDS.has(part.kind ?? "")) continue;
      const nq = normalizeTitle(quote.replace(/\s+/g, " "));
      if (!nq || !haystack.includes(nq)) continue;
      if (!nq.includes(normalizeTitle(title))) continue;
      const artists = Array.isArray(it.artists) ? it.artists.filter((a) => typeof a === "string") : [];
      const ref = { kind: part.kind, ...typeof part.number === "number" ? { number: part.number } : {} };
      out.push({ part: ref, role, position: typeof it.position === "string" ? it.position : void 0, title, artists, evidence: { provider, url, quote, fetchedAt: now } });
    }
    return out;
  }
  function wikiLlmProvider(opts) {
    const f = opts.fetchImpl ?? fetch;
    const now = opts.now ?? (() => (/* @__PURE__ */ new Date()).toISOString());
    const api2 = "https://en.wikipedia.org/w/api.php";
    const get = async (params) => {
      const res = await f(`${api2}?${new URLSearchParams({ format: "json", origin: "*", ...params })}`, { headers: opts.userAgent ? { "User-Agent": opts.userAgent } : {} });
      if (!res.ok) throw new Error(`HTTP ${res.status} from Wikipedia`);
      return await res.json();
    };
    return {
      name: "wikipedia+llm",
      async discover(media) {
        const found = await get({ action: "query", list: "search", srsearch: `${media.title} ${media.type === "anime" ? "anime" : ""}`.trim(), srlimit: String(opts.maxPages ?? 3) });
        const titles = (found.query?.search ?? []).map((r) => r.title);
        const claims = [];
        for (const t of titles) {
          const page = await get({ action: "query", prop: "extracts", explaintext: "1", exlimit: "1", titles: t });
          const text = Object.values(page.query?.pages ?? {})[0]?.extract ?? "";
          if (!text) continue;
          const url = `https://en.wikipedia.org/wiki/${encodeURIComponent(t.replace(/ /g, "_"))}`;
          const raw = await opts.complete(PROMPT(media.title, text.slice(0, 3e4)));
          claims.push(...parseClaims(raw, text, url, now()));
        }
        return claims;
      }
    };
  }
  function anthropicComplete(apiKey, model = "claude-haiku-5-5", fetchImpl = fetch, browser = false) {
    return async (prompt) => {
      const res = await fetchImpl("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: { "content-type": "application/json", "x-api-key": apiKey, "anthropic-version": "2023-06-01", ...browser ? { "anthropic-dangerous-direct-browser-access": "true" } : {} },
        body: JSON.stringify({ model, max_tokens: 4e3, messages: [{ role: "user", content: prompt }] })
      });
      if (!res.ok) throw new Error(`HTTP ${res.status} from Anthropic API`);
      const data = await res.json();
      return (data.content ?? []).filter((c) => c.type === "text").map((c) => c.text ?? "").join("");
    };
  }

  // src/matching/match.ts
  function versionsCompatible(a, b) {
    if (a === b) return true;
    const loose = /* @__PURE__ */ new Set(["original", "full", "unknown"]);
    return loose.has(a) && loose.has(b);
  }
  function scoreMatch(claim, cand) {
    const reasons = [];
    const claimVersion = classifyVersion(claim.title);
    const candVersion = classifyVersion(cand.title, cand.disambiguation);
    if (!versionsCompatible(claimVersion, candVersion)) {
      return { score: 0, versionCompatible: false, reasons: [`version mismatch: ${claimVersion} vs ${candVersion}`] };
    }
    const titleSim = similarity(normalizeTitle(claim.title), normalizeTitle(cand.title));
    const claimArtists = claim.artists.map(normalizeArtist).filter(Boolean);
    const candArtists = cand.artists.map(normalizeArtist).filter(Boolean);
    const artistHit = claimArtists.length === 0 ? 0 : claimArtists.filter((a) => candArtists.some((c) => similarity(a, c) >= 0.85)).length / claimArtists.length;
    let score = titleSim * 0.55 + artistHit * 0.4;
    reasons.push(`title ${titleSim.toFixed(2)}`, `artist ${artistHit.toFixed(2)}`);
    if (claim.durationSec && cand.durationSec && claimVersion !== "tv_size") {
      const diff = Math.abs(claim.durationSec - cand.durationSec);
      if (diff <= 5) {
        score += 0.05;
        reasons.push("duration agrees");
      } else if (diff > 30) {
        score -= 0.15;
        reasons.push(`duration differs by ${diff}s`);
      }
    }
    if (artistHit === 0) score = Math.min(score, 0.5);
    return { score: Math.max(0, Math.min(1, score)), versionCompatible: true, reasons };
  }
  function bestMatch(claim, candidates) {
    let best;
    for (const candidate of candidates) {
      const result = scoreMatch(claim, candidate);
      if (result.versionCompatible && (!best || result.score > best.result.score)) best = { candidate, result };
    }
    return best;
  }

  // src/app/discover.ts
  var CONFIRM_SCORE = 0.8;
  function groupKey(c) {
    const part = `${c.part.kind}:${c.part.number ?? "-"}`;
    return [part, c.role, normalizeTitle(c.title), classifyVersion(c.title)].join("|");
  }
  async function collectClaims(media, providers) {
    const errors = [];
    const claims = [];
    for (const p of providers) {
      try {
        claims.push(...await p.discover(media));
      } catch (e) {
        errors.push(`${p.name}: ${e instanceof Error ? e.message : String(e)}`);
      }
    }
    return { claims, errors };
  }
  async function buildTracks(media, claims, resolver) {
    const errors = [];
    const groups = /* @__PURE__ */ new Map();
    for (const c of claims) {
      const k = groupKey(c);
      groups.set(k, [...groups.get(k) ?? [], c]);
    }
    const tracks = [];
    let n = 0;
    for (const group of groups.values()) {
      const first = group[0];
      const evidence = group.map((g) => g.evidence);
      const sources = new Set(evidence.map((e) => e.provider)).size;
      const artists = [...new Map(group.flatMap((g) => g.artists).map((a) => [normalizeArtist(a), a])).values()];
      const merged = { ...first, artists };
      let recording;
      let matchScore;
      if (resolver) {
        try {
          const m = bestMatch(merged, await resolver.resolve(first.title, artists));
          if (m) {
            recording = m.candidate;
            matchScore = m.result.score;
          }
        } catch (e) {
          errors.push(`${resolver.name}: ${e instanceof Error ? e.message : String(e)}`);
        }
      }
      const matched = (matchScore ?? 0) >= CONFIRM_SCORE;
      const status = matched && sources >= 2 ? "confirmed" : matched || sources >= 2 ? "suggested" : "unverified";
      const confidence = Math.min(1, 0.3 + 0.2 * Math.min(sources - 1, 2) + 0.3 * (matchScore ?? 0));
      tracks.push({
        id: `${media.id}-t${++n}`,
        part: first.part,
        role: first.role,
        position: first.position,
        title: first.title,
        artists,
        version: classifyVersion(first.title),
        recording: matched ? recording : void 0,
        matchScore,
        confidence: Math.round(confidence * 100) / 100,
        status,
        evidence
      });
    }
    return { tracks, errors };
  }

  // src/links/platforms.ts
  var PLATFORMS = ["spotify", "apple", "youtube", "youtubeMusic", "deezer"];
  function searchUrl(platform, q) {
    const e = encodeURIComponent(q);
    switch (platform) {
      case "spotify":
        return `https://open.spotify.com/search/${e}`;
      case "apple":
        return `https://music.apple.com/search?term=${e}`;
      case "youtube":
        return `https://www.youtube.com/results?search_query=${e}`;
      case "youtubeMusic":
        return `https://music.youtube.com/search?q=${e}`;
      case "deezer":
        return `https://www.deezer.com/search/${e}`;
    }
  }
  function buildLinks(track, resolved = []) {
    const q = `${track.title} ${track.artists[0] ?? ""}`.trim();
    return PLATFORMS.map((platform) => resolved.find((r) => r.platform === platform) ?? { platform, url: searchUrl(platform, q), kind: "search" });
  }

  // src/server/runner.ts
  var STEP_LABELS = {
    media: "Resolving media information",
    themes: "Finding theme songs and inserts",
    releases: "Discovering soundtrack releases",
    matching: "Matching tracks and artists",
    links: "Fetching platform links"
  };
  function newSteps() {
    return Object.keys(STEP_LABELS).map((key) => ({ key, label: STEP_LABELS[key], state: "pending" }));
  }
  var msg = (e) => e instanceof Error ? e.message : String(e);
  async function runDiscovery(media, deps, onStep) {
    const errors = [];
    onStep("media", "done", media.title);
    onStep("themes", "running");
    const collected = await collectClaims(media, deps.providers);
    errors.push(...collected.errors);
    onStep("themes", "done", `${collected.claims.length} claims from ${deps.providers.length} sources`);
    onStep("releases", "running");
    const releases = [];
    for (const p of deps.providers) {
      if (!p.releases) continue;
      try {
        releases.push(...await p.releases(media));
      } catch (e) {
        errors.push(`${p.name} (releases): ${msg(e)}`);
      }
    }
    onStep("releases", "done", `${releases.length} releases`);
    onStep("matching", "running");
    const built = await buildTracks(media, collected.claims, deps.recordingResolver);
    errors.push(...built.errors);
    onStep("matching", "done", `${built.tracks.length} tracks`);
    onStep("links", "running");
    const tracks = [];
    for (const t of built.tracks) {
      const resolved = [];
      for (const lr of deps.linkResolvers) {
        try {
          resolved.push(...await lr.resolve(t));
        } catch (e) {
          errors.push(`${lr.name}: ${msg(e)}`);
          break;
        }
      }
      tracks.push({ ...t, links: buildLinks(t, resolved) });
    }
    onStep("links", "done", `${tracks.length} tracks linked`);
    return {
      media,
      tracks,
      releases,
      errors: [...new Set(errors)],
      sources: [.../* @__PURE__ */ new Set([...deps.providers.map((p) => p.name), ...deps.recordingResolver ? [deps.recordingResolver.name] : []])],
      generatedAt: (/* @__PURE__ */ new Date()).toISOString()
    };
  }

  // src/browser/browserApi.ts
  var SETTINGS_KEY = "mmde.settings.v1";
  var RESULTS_KEY = "mmde.results.v1";
  function safeStorage(storage) {
    try {
      const s = storage ?? globalThis.localStorage;
      s.getItem("x");
      return s;
    } catch {
      return void 0;
    }
  }
  function createBrowserApi(opts) {
    const store = safeStorage(opts.storage);
    const memory = /* @__PURE__ */ new Map();
    const f = opts.fetchImpl ?? ((...a) => fetch(...a));
    const readSettings = () => {
      try {
        return { live: true, anthropicKey: "", ...JSON.parse(store?.getItem(SETTINGS_KEY) ?? "{}") };
      } catch {
        return { live: true, anthropicKey: "" };
      }
    };
    const readResults = () => {
      try {
        return JSON.parse(store?.getItem(RESULTS_KEY) ?? "{}");
      } catch {
        return {};
      }
    };
    const view = (r) => ({ ...r, groups: organize(r.tracks) });
    return {
      modeLabel: "direct in browser (no server)",
      settings: {
        get: readSettings,
        set: (s) => {
          try {
            store?.setItem(SETTINGS_KEY, JSON.stringify(s));
          } catch {
          }
        }
      },
      async search(q) {
        const st = readSettings();
        const resolvers = [seedMediaResolver(opts.seeds)];
        if (st.live) resolvers.push(aniListResolver(f));
        const results = [];
        const errors = [];
        const seen = /* @__PURE__ */ new Set();
        for (const r of resolvers) {
          try {
            for (const m of await r.search(q)) {
              const k = normalizeTitle(m.title);
              if (!seen.has(k)) {
                seen.add(k);
                results.push(m);
              }
            }
          } catch (e) {
            errors.push(`${r.name}: ${e instanceof Error ? e.message : String(e)}`);
          }
        }
        return { results, errors, sources: resolvers.map((r) => r.name) };
      },
      async getResult(id) {
        const r = memory.get(id) ?? readResults()[id];
        return r ? view(r) : null;
      },
      async discover(media, onJob) {
        const st = readSettings();
        const providers = opts.seeds.map((s) => curatedProvider(s));
        if (st.live && st.anthropicKey) providers.push(wikiLlmProvider({ complete: anthropicComplete(st.anthropicKey, void 0, f, true), fetchImpl: f }));
        const steps = newSteps();
        const emit = () => onJob({ steps: steps.map((s) => ({ ...s })) });
        emit();
        const result = await runDiscovery(
          media,
          { providers, recordingResolver: st.live ? musicBrainzResolver(null, f) : void 0, linkResolvers: [] },
          (key, state, detail) => {
            const s = steps.find((x) => x.key === key);
            s.state = state;
            s.detail = detail;
            emit();
          }
        );
        memory.set(media.id, result);
        try {
          const all = readResults();
          all[media.id] = result;
          store?.setItem(RESULTS_KEY, JSON.stringify(all));
        } catch {
        }
        return view(result);
      }
    };
  }

  // src/browser/serverApi.ts
  function createServerApi() {
    const call = async (path, init) => {
      const r = await fetch(path, init);
      const j = await r.json().catch(() => ({}));
      if (!r.ok) throw Object.assign(new Error(j.error || `HTTP ${r.status}`), { status: r.status });
      return j;
    };
    return {
      modeLabel: "server (http://localhost)",
      async search(q) {
        return call(`/api/search?q=${encodeURIComponent(q)}`);
      },
      async getResult(id) {
        try {
          return await call(`/api/media/${encodeURIComponent(id)}`);
        } catch (e) {
          if (e.status === 404) return null;
          throw e;
        }
      },
      async discover(media, onJob) {
        const { jobId } = await call("/api/discover", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ media }) });
        for (; ; ) {
          const job = await call(`/api/jobs/${jobId}`);
          onJob({ steps: job.steps });
          if (job.state === "error") throw new Error(job.error || "discovery failed");
          if (job.state === "done") break;
          await new Promise((r) => setTimeout(r, 500));
        }
        return await call(`/api/media/${encodeURIComponent(media.id)}`);
      }
    };
  }

  // src/browser/diagnostics.ts
  var clip = (s, n = 200) => s.length > n ? s.slice(0, n) + "..." : s;
  function buildDiagnostics(r, c) {
    const failed = (name) => r.errors.filter((e) => e.startsWith(`${name}:`) || e.startsWith(`${name} (`));
    const lines = [];
    lines.push("MMDE DIAGNOSTICS");
    lines.push(`generated: ${c.now}`);
    lines.push(`result generatedAt: ${r.generatedAt}`);
    lines.push(`mode: ${c.modeLabel}`);
    lines.push(`live providers: ${c.live == null ? "n/a" : c.live ? "on" : "off"}; AI extractor key set: ${c.hasApiKey == null ? "n/a" : c.hasApiKey ? "yes" : "no"}`);
    if (c.url) lines.push(`page: ${c.url}`);
    if (c.userAgent) lines.push(`browser: ${c.userAgent}`);
    lines.push("");
    lines.push(`MEDIA: ${r.media.title} (${r.media.type}${r.media.year ? ", " + r.media.year : ""}) id=${r.media.id} externalIds=${JSON.stringify(r.media.externalIds)}`);
    if (c.lastSearch) {
      lines.push(`LAST SEARCH: "${c.lastSearch.query}" -> ${c.lastSearch.count} results from [${c.lastSearch.sources.join(", ")}]` + (c.lastSearch.errors.length ? `; errors: ${c.lastSearch.errors.join(" | ")}` : "; no errors"));
    }
    lines.push("");
    lines.push("PROVIDERS (configured -> errors reported)");
    for (const s of r.sources) {
      const f = failed(s);
      lines.push(`- ${s}: ${f.length ? "ERRORS: " + f.join(" | ") : "no error reported"}`);
    }
    const other = r.errors.filter((e) => !r.sources.some((s) => e.startsWith(`${s}:`) || e.startsWith(`${s} (`)));
    if (other.length) lines.push(`other errors: ${other.join(" | ")}`);
    lines.push(`all errors (${r.errors.length}): ${r.errors.length ? r.errors.join(" | ") : "none"}`);
    lines.push("");
    const counts = { confirmed: 0, suggested: 0, unverified: 0 };
    for (const t of r.tracks) counts[t.status]++;
    lines.push(`TRACKS: ${r.tracks.length} total; confirmed ${counts.confirmed}, suggested ${counts.suggested}, unverified ${counts.unverified}`);
    for (const t of r.tracks) {
      const part = t.part.number != null ? `${t.part.kind} ${t.part.number}` : t.part.kind;
      lines.push(`- [${t.status}] ${part} / ${t.role}${t.position ? " " + t.position : ""}: "${t.title}" - ${t.artists.join(", ") || "unknown"} | version=${t.version} confidence=${t.confidence} matchScore=${t.matchScore ?? "none"}` + (t.recording ? ` | mbid=${t.recording.mbid ?? "-"} isrc=${t.recording.isrcs.join(",") || "-"}` : " | no recording match"));
      for (const e of t.evidence) lines.push(`    evidence: ${e.provider} ${e.url ?? "(no url)"}${e.quote ? ` "${clip(e.quote)}"` : ""}`);
      const resolved = t.links.filter((l) => l.kind === "resolved").map((l) => l.platform);
      lines.push(`    links: ${resolved.length ? "resolved=" + resolved.join(",") : "all search links (none resolved)"}`);
    }
    lines.push("");
    lines.push(`RELEASES: ${r.releases.length}`);
    for (const x of r.releases) lines.push(`- ${x.kind} "${x.title}" - ${x.artists.join(", ")}${x.label ? " | " + x.label : ""}${x.trackCount ? " | " + x.trackCount + " tracks" : ""} | source ${x.evidence.url ?? "(none)"}`);
    return lines.join("\n");
  }

  // src/browser/ui.js
  var $app;
  var api;
  var lastSearch = null;
  var mediaCache = /* @__PURE__ */ new Map();
  var el = (tag, attrs = {}, ...kids) => {
    const n = document.createElement(tag);
    for (const [k, v] of Object.entries(attrs)) {
      if (k === "class") n.className = v;
      else if (k.startsWith("on")) n.addEventListener(k.slice(2), v);
      else if (v !== false && v != null) n.setAttribute(k, v);
    }
    for (const kid of kids.flat()) if (kid != null && kid !== false) n.append(kid.nodeType ? kid : document.createTextNode(String(kid)));
    return n;
  };
  var safeUrl = (u) => {
    try {
      const x = new URL(u);
      return x.protocol === "http:" || x.protocol === "https:" ? x.href : null;
    } catch {
      return null;
    }
  };
  var PLATFORM_LABEL = { spotify: "Spotify", apple: "Apple Music", youtube: "YouTube", youtubeMusic: "YouTube Music", deezer: "Deezer" };
  var ROLE_FILTERS = ["All", "Openings", "Endings", "Insert Songs", "Character Songs", "OST", "Original Score"];
  function landing() {
    const input = el("input", { class: "search", type: "search", placeholder: "Search an anime, movie, game or show...", autocomplete: "off", "aria-label": "Search media" });
    const suggest = el("div", { class: "suggest", hidden: true });
    const status = el("div", { class: "note" });
    let timer = 0, seq = 0;
    const run = async () => {
      const q = input.value.trim();
      const mine = ++seq;
      if (q.length < 2) {
        suggest.hidden = true;
        status.textContent = "";
        return;
      }
      try {
        const r = await api.search(q);
        if (mine !== seq) return;
        lastSearch = { query: q, sources: r.sources, errors: r.errors, count: r.results.length };
        suggest.replaceChildren(...r.results.map((m) => {
          mediaCache.set(m.id, m);
          return el(
            "button",
            { type: "button", onclick: () => {
              location.hash = `#/media/${encodeURIComponent(m.id)}`;
            } },
            m.title,
            el("small", {}, `${m.type}${m.year ? " \xB7 " + m.year : ""}`)
          );
        }));
        suggest.hidden = r.results.length === 0;
        status.textContent = r.results.length ? "" : `No results from: ${r.sources.join(", ")}.` + (r.errors.length ? ` Errors: ${r.errors.join("; ")}` : "");
      } catch (e) {
        status.textContent = `Search failed: ${e.message}`;
      }
    };
    input.addEventListener("input", () => {
      clearTimeout(timer);
      timer = setTimeout(run, 250);
    });
    const examples = ["That Time I Got Reincarnated as a Slime", "Jujutsu Kaisen", "Attack on Titan", "Naruto"];
    $app.replaceChildren(
      el(
        "section",
        { class: "hero" },
        el("h1", {}, "Know the Title.", el("br"), el("em", {}, "Discover the Music.")),
        el("p", {}, "Search a title. MMDE finds its openings, endings, inserts and soundtracks, then links you to where the music lives."),
        el("div", { class: "searchwrap" }, input, suggest),
        status,
        el("div", { class: "note" }, "Try:"),
        el("div", { class: "chips" }, examples.map((t) => el("button", { class: "chip", type: "button", onclick: () => {
          input.value = t;
          input.focus();
          run();
        } }, t))),
        el("div", { class: "note" }, "Without live providers only the local sample (Slime) is known. Other titles need live providers."),
        el("div", { class: "note" }, `Mode: ${api.modeLabel}`),
        settingsPanel()
      )
    );
    input.focus();
  }
  function header(media) {
    return el("div", { class: "card" }, el("div", { class: "mh" }, el(
      "div",
      {},
      el("h2", {}, media.title),
      el(
        "div",
        { class: "meta" },
        el("span", { class: "tag" }, media.type),
        media.year ? el("span", { class: "tag" }, String(media.year)) : null,
        ...Object.entries(media.externalIds || {}).map(([k, v]) => el("span", { class: "tag" }, `${k}:${v}`))
      )
    )));
  }
  function progressView(job) {
    return el(
      "div",
      { class: "card" },
      el("strong", {}, "Adding to discovery"),
      el("ul", { class: "progress" }, job.steps.map((s) => el(
        "li",
        {},
        el("span", { class: `dot ${s.state}` }, s.state === "done" ? "\u2713" : s.state === "error" ? "!" : ""),
        el("span", {}, s.label),
        s.detail ? el("small", {}, s.detail) : null
      )))
    );
  }
  function trackRow(t) {
    const open = () => row.parentElement.classList.toggle("open");
    const links = t.links.map((l) => {
      const href = safeUrl(l.url);
      return href ? el(
        "a",
        { class: `plat ${l.kind}`, href, onclick: (e) => e.stopPropagation(), target: "_blank", rel: "noopener noreferrer", title: l.kind === "search" ? "Search link, not a verified match" : "Matched item" },
        PLATFORM_LABEL[l.platform] + (l.kind === "search" ? " (search)" : "")
      ) : null;
    });
    const row = el(
      "div",
      { class: "row", onclick: open, role: "button", tabindex: "0", onkeydown: (e) => {
        if (e.key === "Enter") open();
      } },
      el("span", { class: "pos" }, t.position || ""),
      el("div", {}, el("div", { class: "tt" }, t.title), el("div", { class: "ta" }, t.artists.join(", ") || "unknown artist")),
      el("div", { class: "right" }, links, el("span", { class: `st ${t.status}`, title: `confidence ${t.confidence}` }, t.status))
    );
    const detail = el(
      "div",
      { class: "detail" },
      el("div", {}, `Version: ${t.version} \xB7 confidence ${t.confidence}` + (t.recording?.mbid ? ` \xB7 MusicBrainz ${t.recording.mbid}` : "") + (t.recording?.isrcs?.length ? ` \xB7 ISRC ${t.recording.isrcs.join(", ")}` : "")),
      el("div", {}, "Evidence:"),
      el("ul", {}, t.evidence.map((e) => {
        const href = safeUrl(e.url);
        return el("li", {}, `${e.provider}: `, href ? el("a", { href, target: "_blank", rel: "noopener noreferrer" }, e.url) : e.url || "no source URL", e.quote ? ` - "${e.quote}"` : "");
      }))
    );
    return el("div", { class: "track" }, row, detail);
  }
  function diagButton(r) {
    const st = api.settings ? api.settings.get() : null;
    const text = () => buildDiagnostics(r, {
      modeLabel: api.modeLabel,
      live: st ? !!st.live : void 0,
      hasApiKey: st ? !!st.anthropicKey : void 0,
      url: location.href,
      userAgent: navigator.userAgent,
      now: (/* @__PURE__ */ new Date()).toISOString(),
      lastSearch: lastSearch || void 0
    });
    const msg2 = el("span", { class: "note" });
    const box = el("pre", { class: "diag", hidden: true });
    const btn = el("button", { class: "btn ghost", type: "button", id: "copy-diag", onclick: async () => {
      const t = text();
      box.textContent = t;
      box.hidden = false;
      try {
        await navigator.clipboard.writeText(t);
        msg2.textContent = "Copied. Paste it into the chat.";
      } catch {
        msg2.textContent = "Could not copy automatically. Select the text below and copy it.";
      }
    } }, "Copy diagnostics");
    return el("span", {}, btn, " ", msg2, box);
  }
  function resultView(r, filter, rerender, onRefresh) {
    const counts = { confirmed: 0, suggested: 0, unverified: 0 };
    r.tracks.forEach((t) => counts[t.status]++);
    const roleLabels = new Set(r.groups.flatMap((g) => g.roles.map((x) => x.role)));
    const parts = r.groups.map((g) => {
      const roles = g.roles.filter((x) => filter === "All" || x.role === filter);
      return roles.length ? el("div", {}, el("h3", { class: "part" }, g.part), roles.map((x) => el("div", {}, el("h4", { class: "role" }, x.role), x.tracks.map(trackRow)))) : null;
    });
    const relevant = r.releases.filter((x) => filter === "All" || filter === "OST" && x.kind === "ost");
    const releases = relevant.length ? el("div", {}, el("h3", { class: "part" }, "Soundtrack releases"), relevant.map((x) => {
      const href = safeUrl(x.evidence.url);
      return el(
        "div",
        { class: "card rel" },
        el(
          "div",
          {},
          el("div", { class: "tt" }, x.title),
          el("div", { class: "ta" }, x.artists.join(", ")),
          el("div", { class: "ta" }, [x.kind.toUpperCase(), x.label, x.trackCount ? `${x.trackCount} tracks` : null, x.date, x.part ? `(${x.part.kind})` : null].filter(Boolean).join(" \xB7 "))
        ),
        el("div", {}, href ? el("a", { href, target: "_blank", rel: "noopener noreferrer" }, "source") : el("span", { class: "ta" }, "no source URL"))
      );
    })) : null;
    const noOst = !roleLabels.has("OST") && !roleLabels.has("Original Score") && !r.releases.some((x) => x.kind === "ost") ? el("div", { class: "empty" }, "No OST or original score found yet for this title. That usually means the sources queried had none, not that none exists.") : null;
    return el(
      "div",
      {},
      header(r.media),
      el(
        "div",
        { class: "card" },
        el(
          "div",
          { class: "meta" },
          `${r.tracks.length} tracks \xB7 `,
          el("span", { class: "st confirmed" }, `${counts.confirmed} confirmed`),
          el("span", { class: "st suggested" }, `${counts.suggested} suggested`),
          el("span", { class: "st unverified" }, `${counts.unverified} unverified`),
          el("span", {}, `sources: ${r.sources.join(", ")}`),
          el("button", { class: "btn ghost", type: "button", onclick: onRefresh }, "Re-discover"),
          diagButton(r)
        ),
        el("div", { class: "chips" }, ROLE_FILTERS.map((f) => el("button", { class: `chip ${f === filter ? "on" : ""}`, type: "button", onclick: () => rerender(f) }, f)))
      ),
      parts,
      releases,
      filter === "All" || filter === "OST" ? noOst : null,
      r.errors.length ? el("div", { class: "card warn" }, "Provider notes: ", r.errors.join(" | ")) : null
    );
  }
  async function mediaPage(id) {
    let filter = "All";
    const show = (r) => {
      const draw = () => $app.replaceChildren(el("a", { href: "#/" }, "\u2190 Back to search"), resultView(r, filter, (f) => {
        filter = f;
        draw();
      }, () => discover(r.media)));
      draw();
    };
    const discover = async (media2) => {
      $app.replaceChildren(el("a", { href: "#/" }, "\u2190 Back to search"), header(media2), el("div", { class: "note" }, "Starting discovery..."));
      try {
        const result = await api.discover(media2, (job) => {
          $app.replaceChildren(el("a", { href: "#/" }, "\u2190 Back to search"), header(media2), progressView(job));
        });
        show(result);
      } catch (e) {
        $app.replaceChildren(el("a", { href: "#/" }, "\u2190 Back to search"), el("div", { class: "card warn" }, `Discovery failed: ${e.message}`));
      }
    };
    let existing = null;
    try {
      existing = await api.getResult(id);
    } catch (e) {
      return $app.replaceChildren(el("div", { class: "card warn" }, e.message));
    }
    if (existing) return show(existing);
    const media = mediaCache.get(id);
    if (!media) {
      location.hash = "#/";
      return;
    }
    discover(media);
  }
  function settingsPanel() {
    const st = api.settings;
    if (!st) return null;
    const cur = st.get();
    const live = el("input", { type: "checkbox", id: "live" });
    live.checked = !!cur.live;
    const key = el("input", { type: "password", id: "akey", placeholder: "optional: Anthropic API key (stored only in this browser)", autocomplete: "off", style: "width:100%;padding:8px;border-radius:8px;border:1px solid var(--line);background:var(--bg);color:var(--text)" });
    key.value = cur.anthropicKey || "";
    const msg2 = el("span", { class: "note" });
    const save = el("button", { class: "btn", type: "button", onclick: () => {
      st.set({ live: live.checked, anthropicKey: key.value.trim() });
      msg2.textContent = "Saved.";
    } }, "Save");
    return el(
      "details",
      { class: "card" },
      el("summary", {}, "Settings"),
      el("label", {}, live, " Use live providers (AniList, MusicBrainz, Wikipedia) directly from this browser"),
      el("div", { class: "note" }, "Your browser cannot set a custom User-Agent; keep usage light. Deezer cannot be called from a browser (no CORS), so platform links stay as search links."),
      el("div", { class: "note" }, "An API key enables the Wikipedia+AI extractor. It is sent only to api.anthropic.com from this browser, but anyone with access to this browser profile can read it."),
      key,
      el("div", {}, save, " ", msg2)
    );
  }
  function route() {
    const m = location.hash.match(/^#\/media\/(.+)$/);
    if (m) mediaPage(decodeURIComponent(m[1]));
    else landing();
  }
  function mountUI(root, apiImpl) {
    $app = root;
    api = apiImpl;
    window.addEventListener("hashchange", route);
    route();
  }

  // src/browser/main.ts
  async function start() {
    const root = document.getElementById("app");
    let api2 = createBrowserApi({ seeds: [slime_sample_default] });
    if (location.protocol.startsWith("http")) {
      try {
        const r = await fetch("/api/health");
        if (r.ok && (await r.json()).ok) api2 = createServerApi();
      } catch {
      }
    }
    mountUI(root, api2);
  }
  void start();
})();
