/* MMDE search bundle. GENERATED by search/build.mjs. Do not edit. */
(() => {
  // search/src/text.js
  var norm = (s) => String(s ?? "").normalize("NFKD").replace(/[̀-ͯ]/g, "").toLowerCase().replace(/&/g, " and ").replace(/[^\p{L}\p{N}]+/gu, " ").trim();
  function baseKey(title2) {
    let t = String(title2 ?? "").replace(/\([^)]*(?:film|tv series|television series|anime|season|series|miniseries|video game|ova|manga|novel)[^)]*\)/gi, " ");
    t = norm(t);
    t = t.replace(/\b(?:season|part|cour|series)\s*(?:\d+|[ivx]+)\b/g, " ").replace(/\b\d+(?:st|nd|rd|th)\s+season\b/g, " ").replace(/\bfinal season\b/g, " ").replace(/\s+/g, " ").trim();
    return t;
  }
  var firstYear = (s) => {
    const m = /\b(18|19|20)\d{2}\b/.exec(String(s ?? ""));
    return m ? Number(m[0]) : void 0;
  };
  function lev(a, b) {
    const prev = Array.from({ length: b.length + 1 }, (_, i) => i);
    for (let i = 1; i <= a.length; i++) {
      let diag = prev[0];
      prev[0] = i;
      for (let j = 1; j <= b.length; j++) {
        const tmp = prev[j];
        prev[j] = Math.min(prev[j] + 1, prev[j - 1] + 1, diag + (a[i - 1] === b[j - 1] ? 0 : 1));
        diag = tmp;
      }
    }
    return prev[b.length];
  }
  var wordSim = (a, b) => a === b ? 1 : !a || !b ? 0 : 1 - lev(a, b) / Math.max(a.length, b.length);

  // search/src/query.js
  var LANGS = /* @__PURE__ */ new Set(["telugu", "hindi", "tamil", "malayalam", "kannada", "bengali", "marathi", "punjabi", "english", "japanese", "korean", "chinese"]);
  var TYPES = { movie: "movie", movies: "movie", film: "movie", films: "movie", anime: "anime", cartoon: "anime", series: "tv", show: "tv", shows: "tv", tv: "tv", serial: "tv", game: "game", games: "game" };
  function parseQuery(raw) {
    const original = String(raw ?? "").trim();
    const tokens = original.split(/\s+/).filter(Boolean);
    let lang = null;
    let type = null;
    const rest = [];
    for (const tok of tokens) {
      const w = tok.toLowerCase();
      if (!lang && LANGS.has(w)) lang = w;
      else if (!type && TYPES[w]) type = TYPES[w];
      else rest.push(tok);
    }
    if (rest.length === 0) return { original, text: original, lang: null, type: null };
    return { original, text: rest.join(" "), lang, type };
  }

  // search/src/sources/anilist.js
  var URL_ = "https://graphql.anilist.co";
  async function gql(fetchImpl, query, variables) {
    const res = await fetchImpl(URL_, {
      method: "POST",
      headers: { "Content-Type": "application/json", Accept: "application/json" },
      body: JSON.stringify({ query, variables })
    });
    if (!res.ok) throw new Error(`HTTP ${res.status} from AniList`);
    const j = await res.json();
    if (j.errors?.length) throw new Error(`AniList: ${j.errors[0].message}`);
    return j.data;
  }
  var SEARCH = `query($q:String){Page(perPage:15){media(search:$q,type:ANIME,sort:SEARCH_MATCH){
  id idMal title{romaji english native} synonyms format episodes status seasonYear startDate{year}
  coverImage{medium} description(asHtml:false) countryOfOrigin}}}`;
  var stripHtml = (s) => String(s ?? "").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
  var title = (t) => t?.english || t?.romaji || t?.native || "";
  function mapAniListMedia(m) {
    const t = title(m.title);
    return {
      id: `anilist:${m.id}`,
      anilistId: m.id,
      malId: m.idMal ?? void 0,
      kind: "anime",
      title: t,
      altTitles: [m.title?.romaji, m.title?.english, m.title?.native, ...m.synonyms ?? []].filter((x) => x && x !== t),
      year: m.seasonYear ?? m.startDate?.year ?? void 0,
      format: m.format ?? void 0,
      episodes: m.episodes ?? void 0,
      poster: m.coverImage?.medium ?? void 0,
      description: stripHtml(m.description).slice(0, 240),
      country: m.countryOfOrigin ?? void 0,
      sources: { anilist: `https://anilist.co/anime/${m.id}` }
    };
  }
  function collapseSeasons(items) {
    const groups = /* @__PURE__ */ new Map();
    for (const it of items) {
      const key = baseKey(it.title) || it.id;
      const cur = groups.get(key);
      if (!cur || (it.year ?? 9999) < (cur.year ?? 9999)) groups.set(key, { ...it, collapsed: (cur?.collapsed ?? 0) + 1 });
      else cur.collapsed = (cur.collapsed ?? 0) + 1;
    }
    return [...groups.values()];
  }
  async function searchAniList(text, fetchImpl) {
    const data = await gql(fetchImpl, SEARCH, { q: text });
    return collapseSeasons((data.Page?.media ?? []).map(mapAniListMedia));
  }
  var FRANCHISE = `query($ids:[Int]){Page(perPage:50){media(id_in:$ids){
  id title{romaji english native} format episodes status startDate{year month day} coverImage{medium}
  relations{edges{relationType(version:2) node{id type title{romaji english native} format episodes status startDate{year month day} coverImage{medium}}}}}}}`;
  var dateKey = (d) => (d?.year ?? 9999) * 1e4 + (d?.month ?? 0) * 100 + (d?.day ?? 0);
  var view = (n) => ({ id: n.id, title: title(n.title), native: n.title?.native, year: n.startDate?.year, episodes: n.episodes ?? void 0, format: n.format, status: n.status, poster: n.coverImage?.medium, url: `https://anilist.co/anime/${n.id}`, _d: dateKey(n.startDate) });
  var clean = ({ _d, ...rest }) => rest;
  var CHAIN = /* @__PURE__ */ new Set(["PREQUEL", "SEQUEL", "PARENT"]);
  async function getAniListFranchise(anilistId, fetchImpl, { maxLevels = 8, maxNodes = 40 } = {}) {
    const nodes = /* @__PURE__ */ new Map();
    const fetched = /* @__PURE__ */ new Set();
    let frontier = [anilistId];
    for (let level = 0; level < maxLevels && frontier.length && fetched.size < maxNodes; level++) {
      const ids = frontier.filter((i) => !fetched.has(i)).slice(0, 25);
      if (!ids.length) break;
      ids.forEach((i) => fetched.add(i));
      const data = await gql(fetchImpl, FRANCHISE, { ids });
      const next = [];
      for (const m of data.Page?.media ?? []) {
        nodes.set(m.id, view(m));
        for (const e of m.relations?.edges ?? []) {
          const n = e.node;
          if (!n || n.type !== "ANIME") continue;
          if (CHAIN.has(e.relationType)) {
            if (!nodes.has(n.id)) nodes.set(n.id, view(n));
            if (!fetched.has(n.id)) next.push(n.id);
          } else if (e.relationType === "SIDE_STORY" && !nodes.has(n.id)) {
            nodes.set(n.id, view(n));
          }
        }
      }
      frontier = [...new Set(next)];
    }
    const all = [...nodes.values()].sort((a, b) => a._d - b._d);
    return {
      seasons: all.filter((n) => n.format === "TV").map(clean),
      movies: all.filter((n) => n.format === "MOVIE").map(clean),
      other: all.filter((n) => n.format && !["TV", "MOVIE"].includes(n.format)).map(clean)
    };
  }
  async function resolveAniListId(titleText, fetchImpl) {
    const items = await searchAniList(titleText, fetchImpl);
    const k = norm(titleText);
    const hit = items.find((i) => [i.title, ...i.altTitles].some((t) => baseKey(t) === baseKey(titleText) || norm(t) === k));
    return hit?.anilistId;
  }

  // search/src/sources/tmdb.js
  var API = "https://api.themoviedb.org/3";
  var IMG = "https://image.tmdb.org/t/p/w154";
  function mapTmdb(r) {
    const isTv = r.media_type === "tv";
    const title2 = r.title || r.name || "";
    return {
      id: `tmdb:${r.media_type}:${r.id}`,
      tmdbId: r.id,
      tmdbType: r.media_type,
      kind: isTv ? "tv" : "movie",
      title: title2,
      altTitles: [r.original_title, r.original_name].filter((x) => x && x !== title2),
      year: firstYear(r.release_date || r.first_air_date),
      language: r.original_language,
      description: (r.overview ?? "").slice(0, 240),
      poster: r.poster_path ? IMG + r.poster_path : void 0,
      popularity: r.popularity ?? 0,
      sources: { tmdb: `https://www.themoviedb.org/${r.media_type}/${r.id}` }
    };
  }
  async function searchTmdb(text, key, fetchImpl) {
    const res = await fetchImpl(`${API}/search/multi?${new URLSearchParams({ api_key: key, query: text, include_adult: "false" })}`);
    if (res.status === 401) throw new Error("TMDB rejected the API key (401)");
    if (!res.ok) throw new Error(`HTTP ${res.status} from TMDB`);
    const j = await res.json();
    return (j.results ?? []).filter((r) => r.media_type === "movie" || r.media_type === "tv").map(mapTmdb);
  }
  async function getTmdbSeasons(id, key, fetchImpl) {
    const res = await fetchImpl(`${API}/tv/${id}?${new URLSearchParams({ api_key: key })}`);
    if (!res.ok) throw new Error(`HTTP ${res.status} from TMDB`);
    const j = await res.json();
    return (j.seasons ?? []).map((s) => ({
      id: s.id,
      title: s.name,
      number: s.season_number,
      episodes: s.episode_count,
      year: firstYear(s.air_date),
      poster: s.poster_path ? IMG + s.poster_path : void 0
    }));
  }

  // search/src/sources/wikipedia.js
  var API2 = "https://en.wikipedia.org/w/api.php";
  var WORK = /film|movie|series|television|anime|animation|animated|\bova\b|video game|miniseries|web series|show|documentary|cartoon|light novel|manga|novel|musical|sitcom|drama/i;
  function inferKind(desc) {
    const d = String(desc ?? "").toLowerCase();
    if (/anime|animated|original video animation|\bova\b/.test(d)) return "anime";
    if (/video game/.test(d)) return "game";
    if (/television|tv series|web series|miniseries|sitcom|\bshow\b/.test(d)) return "tv";
    if (/\bfilm\b|\bmovie\b/.test(d)) return "movie";
    if (/novel|manga/.test(d)) return "book";
    return "other";
  }
  function inferLanguage(desc) {
    const m = /\b([A-Z][a-z]+)-language\b/.exec(String(desc ?? ""));
    return m ? m[1] : void 0;
  }
  function mapWikipediaPages(pages) {
    return Object.values(pages ?? {}).sort((a, b) => (a.index ?? 0) - (b.index ?? 0)).filter((p) => WORK.test(p.description ?? "")).map((p) => ({
      id: `wikipedia:${p.pageid}`,
      kind: inferKind(p.description),
      title: p.title,
      altTitles: [],
      year: firstYear(p.description),
      language: inferLanguage(p.description),
      description: p.description ?? "",
      poster: p.thumbnail?.source,
      sources: { wikipedia: `https://en.wikipedia.org/wiki/${encodeURIComponent(p.title.replace(/ /g, "_"))}` },
      wikiTitle: p.title
    }));
  }
  var TYPE_WORD = { movie: "film", tv: "television series", anime: "anime", game: "video game" };
  async function searchWikipedia(parsed, fetchImpl) {
    const q = [parsed.text, parsed.lang, TYPE_WORD[parsed.type]].filter(Boolean).join(" ");
    const params = new URLSearchParams({
      action: "query",
      format: "json",
      origin: "*",
      generator: "search",
      gsrsearch: q,
      gsrlimit: "20",
      gsrnamespace: "0",
      prop: "description|pageimages",
      piprop: "thumbnail",
      pithumbsize: "120",
      redirects: "1"
    });
    const res = await fetchImpl(`${API2}?${params}`);
    if (!res.ok) throw new Error(`HTTP ${res.status} from Wikipedia`);
    const j = await res.json();
    return mapWikipediaPages(j.query?.pages);
  }
  async function getWikipediaSummary(title2, fetchImpl) {
    const params = new URLSearchParams({ action: "query", format: "json", origin: "*", prop: "extracts", exintro: "1", explaintext: "1", exchars: "700", titles: title2, redirects: "1" });
    const res = await fetchImpl(`${API2}?${params}`);
    if (!res.ok) throw new Error(`HTTP ${res.status} from Wikipedia`);
    const j = await res.json();
    return Object.values(j.query?.pages ?? {})[0]?.extract ?? "";
  }

  // search/src/search.js
  var keysOf = (r) => [r.title, ...r.altTitles ?? []].map(baseKey).filter(Boolean);
  function score(r, parsed) {
    const q = norm(parsed.text);
    const qk = baseKey(parsed.text);
    let best = 0;
    for (const k of keysOf(r)) {
      if (k === qk || k === q) best = Math.max(best, 100);
      else if (k.startsWith(q)) best = Math.max(best, 75);
      else if ((" " + k + " ").includes(" " + q + " ")) best = Math.max(best, 60);
      else {
        const qt = q.split(" ").filter(Boolean);
        const kt = k.split(" ").filter(Boolean);
        if (qt.length && kt.length) {
          const sims = qt.map((t) => Math.max(...kt.map((w) => wordSim(t, w))));
          const strong = sims.filter((x) => x >= 0.8);
          if (strong.length) best = Math.max(best, Math.round(strong.reduce((a, b) => a + b, 0) / qt.length * 55));
        }
      }
    }
    if (parsed.type && r.kind === parsed.type) best += 15;
    if (parsed.lang) {
      const l = parsed.lang.slice(0, 2);
      const lang = String(r.language ?? "").toLowerCase();
      if (lang.startsWith(l) || lang.includes(parsed.lang) || String(r.description ?? "").toLowerCase().includes(parsed.lang)) best += 20;
    }
    if (r.kind === "book") best -= 10;
    if (r.sources?.anilist) best += 5;
    return best;
  }
  function mergeResults(lists) {
    const out = [];
    for (const r of lists.flat()) {
      const ks = new Set(keysOf(r));
      const hit = out.find((o) => keysOf(o).some((k) => ks.has(k)));
      if (!hit) {
        out.push({ ...r, sources: { ...r.sources } });
        continue;
      }
      hit.sources = { ...hit.sources, ...r.sources };
      hit.altTitles = [.../* @__PURE__ */ new Set([...hit.altTitles ?? [], ...r.altTitles ?? [], ...r.title !== hit.title ? [r.title] : []])];
      hit.poster ??= r.poster;
      hit.year ??= r.year;
      hit.language ??= r.language;
      if (!hit.description || r.description && hit.description.length < 20) hit.description = r.description;
      hit.anilistId ??= r.anilistId;
      hit.tmdbId ??= r.tmdbId;
      hit.tmdbType ??= r.tmdbType;
      hit.wikiTitle ??= r.wikiTitle;
      if (hit.kind !== "anime" && r.kind === "anime") hit.kind = "anime";
    }
    return out;
  }
  async function searchAll(raw, { fetchImpl = (...a) => fetch(...a), tmdbKey = "" } = {}) {
    const parsed = parseQuery(raw);
    if (!parsed.text) return { parsed, results: [], notes: [] };
    const plan = [];
    const nonJapanese = parsed.lang && parsed.lang !== "japanese";
    if (!nonJapanese && parsed.type !== "game") plan.push(["AniList", () => searchAniList(parsed.text, fetchImpl)]);
    plan.push(["Wikipedia", () => searchWikipedia(parsed, fetchImpl)]);
    if (tmdbKey && parsed.type !== "anime") plan.push(["TMDB", () => searchTmdb(parsed.text, tmdbKey, fetchImpl)]);
    const settled = await Promise.allSettled(plan.map(([, fn]) => fn()));
    const notes = [];
    const lists = [];
    settled.forEach((s, i) => {
      const source = plan[i][0];
      if (s.status === "fulfilled") {
        lists.push(s.value);
        notes.push({ source, ok: true, count: s.value.length });
      } else notes.push({ source, ok: false, count: 0, error: s.reason instanceof Error ? s.reason.message : String(s.reason) });
    });
    if (!tmdbKey) notes.push({ source: "TMDB", ok: true, count: 0, skipped: "no API key (optional)" });
    const results = mergeResults(lists).map((r) => ({ ...r, _score: score(r, parsed) })).sort((a, b) => b._score - a._score).map(({ _score, ...r }) => r);
    return { parsed, results, notes };
  }
  async function getDetail(result, { fetchImpl = (...a) => fetch(...a), tmdbKey = "" } = {}) {
    const detail = { franchise: null, tmdbSeasons: null, summary: "", notes: [] };
    const tasks = [];
    if (result.kind === "anime" || result.anilistId) {
      tasks.push((async () => {
        try {
          const id = result.anilistId ?? await resolveAniListId(result.title, fetchImpl);
          if (id) detail.franchise = await getAniListFranchise(id, fetchImpl);
          else detail.notes.push("AniList: no matching entry, so no season list");
        } catch (e) {
          detail.notes.push(`AniList: ${e.message}`);
        }
      })());
    }
    if (result.tmdbType === "tv" && tmdbKey) {
      tasks.push(getTmdbSeasons(result.tmdbId, tmdbKey, fetchImpl).then((s) => {
        detail.tmdbSeasons = s;
      }).catch((e) => detail.notes.push(`TMDB: ${e.message}`)));
    }
    if (result.wikiTitle) {
      tasks.push(getWikipediaSummary(result.wikiTitle, fetchImpl).then((s) => {
        detail.summary = s;
      }).catch((e) => detail.notes.push(`Wikipedia: ${e.message}`)));
    }
    await Promise.all(tasks);
    return detail;
  }

  // search/src/ui.js
  var el = (tag, attrs = {}, ...kids) => {
    const n = document.createElement(tag);
    for (const [k, v] of Object.entries(attrs)) {
      if (k === "class") n.className = v;
      else if (k.startsWith("on")) n.addEventListener(k.slice(2), v);
      else if (v != null && v !== false) n.setAttribute(k, v);
    }
    for (const kid of kids.flat()) if (kid != null && kid !== false) n.append(kid.nodeType ? kid : document.createTextNode(String(kid)));
    return n;
  };
  var safe = (u) => {
    try {
      const x = new URL(u);
      return /^https?:$/.test(x.protocol) ? x.href : null;
    } catch {
      return null;
    }
  };
  var KEY = "mmde.search.tmdbKey";
  var store = {
    get() {
      try {
        return localStorage.getItem(KEY) || "";
      } catch {
        return "";
      }
    },
    set(v) {
      try {
        localStorage.setItem(KEY, v);
      } catch {
      }
    }
  };
  var LABEL = { anime: "Anime", movie: "Movie", tv: "TV", game: "Game", book: "Book", other: "Other" };
  function card(r, onOpen) {
    const link = (name, url) => {
      const h = safe(url);
      return h ? el("a", { class: "src", href: h, target: "_blank", rel: "noopener noreferrer", onclick: (e) => e.stopPropagation() }, name) : null;
    };
    return el(
      "li",
      { class: "card", tabindex: "0", role: "button", onclick: () => onOpen(r), onkeydown: (e) => {
        if (e.key === "Enter") onOpen(r);
      } },
      r.poster && safe(r.poster) ? el("img", { class: "poster", src: safe(r.poster), alt: "", loading: "lazy" }) : el("div", { class: "poster ph" }, (r.title[0] || "?").toUpperCase()),
      el(
        "div",
        { class: "meta" },
        el("div", { class: "title" }, r.title),
        el("div", { class: "sub" }, [LABEL[r.kind] || r.kind, r.year, r.language, r.format && r.format !== "TV" ? r.format : null, r.episodes ? `${r.episodes} eps` : null].filter(Boolean).join(" \xB7 ")),
        r.description ? el("div", { class: "desc" }, r.description) : null,
        el("div", { class: "srcs" }, link("AniList", r.sources.anilist), link("Wikipedia", r.sources.wikipedia), link("TMDB", r.sources.tmdb))
      )
    );
  }
  function group(title2, items, noteFn) {
    if (!items?.length) return null;
    return el(
      "section",
      {},
      el("h3", {}, title2, el("span", { class: "count" }, ` ${items.length}`)),
      el("ol", { class: "rows" }, items.map((s, i) => el(
        "li",
        { class: "row" },
        el("span", { class: "num" }, noteFn ? noteFn(s, i) : String(i + 1)),
        el(
          "div",
          {},
          el("div", { class: "title" }, safe(s.url) ? el("a", { href: safe(s.url), target: "_blank", rel: "noopener noreferrer" }, s.title) : s.title),
          el("div", { class: "sub" }, [s.year, s.format, s.episodes ? `${s.episodes} episodes` : null, s.status ? s.status.toLowerCase().replace("_", " ") : null].filter(Boolean).join(" \xB7 "))
        )
      )))
    );
  }
  function mount(root) {
    const input = el("input", { id: "q", class: "search", type: "search", placeholder: "Search an anime, movie or show... (try: tensura, og telugu movie, bahubali)", autocomplete: "off", "aria-label": "Search" });
    const status = el("div", { id: "status", class: "status" });
    const list = el("ul", { id: "results", class: "cards" });
    const detail = el("div", { id: "detail", hidden: true });
    const keyInput = el("input", { id: "tmdbkey", type: "password", placeholder: "optional TMDB API key", autocomplete: "off" });
    keyInput.value = store.get();
    const keyMsg = el("span", { class: "note" });
    const settings = el(
      "details",
      { class: "settings" },
      el("summary", {}, "Settings (optional)"),
      el("p", { class: "note" }, "AniList and Wikipedia need no key. Add your own free TMDB key to also search TMDB (best for movies, TV and Indian cinema, and gives TV seasons). It stays in this browser only."),
      el("p", { class: "note" }, el("a", { href: "https://www.themoviedb.org/settings/api", target: "_blank", rel: "noopener noreferrer" }, "Get a free TMDB key")),
      keyInput,
      el("button", { class: "btn", type: "button", onclick: () => {
        store.set(keyInput.value.trim());
        keyMsg.textContent = "Saved. Search again.";
      } }, "Save"),
      " ",
      keyMsg
    );
    let seq = 0;
    let timer = 0;
    const run = async () => {
      const q = input.value.trim();
      const mine = ++seq;
      detail.hidden = true;
      list.hidden = false;
      if (q.length < 2) {
        list.replaceChildren();
        status.textContent = "";
        return;
      }
      status.textContent = "Searching...";
      const out = await searchAll(q, { tmdbKey: store.get() });
      if (mine !== seq) return;
      list.replaceChildren(...out.results.map((r) => card(r, open)));
      const parts = out.notes.map((n) => n.skipped ? `${n.source} off` : n.ok ? `${n.source} ${n.count}` : `${n.source} FAILED: ${n.error}`);
      const hint = [out.parsed.lang && `language: ${out.parsed.lang}`, out.parsed.type && `type: ${out.parsed.type}`].filter(Boolean).join(", ");
      status.textContent = `${out.results.length} results${hint ? ` (${hint})` : ""} \xB7 ${parts.join(" \xB7 ")}`;
      if (!out.results.length) list.replaceChildren(el("li", { class: "empty" }, "No results. Check the sources above for errors, or try another spelling."));
    };
    async function open(r) {
      list.hidden = true;
      detail.hidden = false;
      detail.replaceChildren(el("button", { class: "btn ghost", type: "button", onclick: () => {
        detail.hidden = true;
        list.hidden = false;
      } }, "\u2190 Results"), el("p", { class: "note" }, "Loading details..."));
      const d = await getDetail(r, { tmdbKey: store.get() });
      const f = d.franchise;
      detail.replaceChildren(...[
        el("button", { class: "btn ghost", type: "button", onclick: () => {
          detail.hidden = true;
          list.hidden = false;
        } }, "\u2190 Results"),
        el(
          "div",
          { class: "head" },
          r.poster && safe(r.poster) ? el("img", { class: "poster big", src: safe(r.poster), alt: "" }) : null,
          el(
            "div",
            {},
            el("h2", {}, r.title),
            el("div", { class: "sub" }, [LABEL[r.kind] || r.kind, r.year, r.language].filter(Boolean).join(" \xB7 ")),
            r.altTitles?.length ? el("div", { class: "sub" }, "Also: " + r.altTitles.slice(0, 5).join(" \xB7 ")) : null,
            el("p", {}, d.summary || r.description || "")
          )
        ),
        f ? el("div", {}, group("Seasons", f.seasons, (s, i) => `S${i + 1}`), el("p", { class: "note" }, 'AniList lists each cour/part as its own entry, so a "season" here can be a part of one.'), group("Movies", f.movies), group("OVAs, specials & more", f.other)) : null,
        d.tmdbSeasons ? group("TMDB seasons", d.tmdbSeasons.map((s) => ({ title: s.title, year: s.year, episodes: s.episodes })), (s, i) => String(d.tmdbSeasons[i].number)) : null,
        d.notes.length ? el("p", { class: "warn" }, d.notes.join(" | ")) : null
      ].filter(Boolean));
    }
    input.addEventListener("input", () => {
      clearTimeout(timer);
      timer = setTimeout(run, 300);
    });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        clearTimeout(timer);
        run();
      }
    });
    root.replaceChildren(
      el("h1", {}, "MMDE ", el("small", {}, "search")),
      el("p", { class: "note" }, "Phase 1: find the title. Anime show seasons. No music yet."),
      input,
      status,
      list,
      detail,
      settings,
      el("p", { class: "foot" }, "Data: AniList (anilist.co), Wikipedia (CC BY-SA), optional TMDB. This product uses the TMDB API but is not endorsed or certified by TMDB.")
    );
    input.focus();
  }

  // search/src/main.js
  mount(document.getElementById("app"));
})();
