// Bundles search/src/main.js into ONE classic script (search/app.js) so search/index.html works when
// double-clicked (file://) with no server. Dev-time only; the built file is committed.
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const here = dirname(fileURLToPath(import.meta.url));
await build({ entryPoints: [join(here, 'src/main.js')], outfile: join(here, 'app.js'), bundle: true, format: 'iife', platform: 'browser', target: 'es2022', legalComments: 'none', banner: { js: '/* MMDE search bundle. GENERATED by search/build.mjs. Do not edit. */' } });
console.log('built search/app.js');
