// Bundles src/browser/main.ts into ONE classic script, web/mmde.js, so index.html works when
// double-clicked (file://) with no server. Dev-time only: the built file is committed.
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
await build({
  entryPoints: [join(root, 'src/browser/main.ts')],
  outfile: join(root, 'web/mmde.js'),
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2022',
  external: ['node:*'],
  loader: { '.json': 'json' },
  legalComments: 'none',
  banner: { js: '/* MMDE browser bundle. GENERATED by scripts/build-web.mjs from src/. Do not edit. */' },
});
console.log('built web/mmde.js');

// The in-browser backend ("beta" / GitHub-only mode): the same providers the server uses, bundled for the page.
await build({
  entryPoints: [join(root, 'src/browser/static-entry.ts')],
  outfile: join(root, 'web/mmde-static.js'),
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2022',
  external: ['node:*'],
  minify: true,
  legalComments: 'none',
  banner: { js: '/* MMDE in-browser backend. GENERATED by scripts/build-web.mjs from src/. Do not edit. */' },
});
console.log('built web/mmde-static.js');
